"""AI Lung CT Analysis - Streamlit web application.

Research prototype for NSCLC-related CT analysis. NOT a medical diagnostic
device. See DISCLAIMER below and README.md for full context.
"""

from __future__ import annotations

import sys
import tempfile
import uuid
from pathlib import Path

import numpy as np
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent))

from src.data.dataset_utils import UnsupportedInputError, load_any
from src.data.preprocessing import preprocess_ct_volume
from src.explainability.gradcam import generate_explanation
from src.features.deep_features import extract_deep_features
from src.features.radiomics_features import RadiomicsExtractionError, extract_radiomic_features
from src.models.classifier import ClassifierUnavailableError
from src.models.model_manager import (
    check_model_files,
    get_device,
    get_gpu_name,
    load_classifier,
    load_pretrained_model,
)
from src.segmentation.roi_extractor import (
    calculate_roi_statistics,
    crop_roi,
    generate_roi_from_detection,
)
from src.utils.config_loader import load_config, load_dataset_config, resolve_path
from src.utils.logging_utils import get_logger
from src.utils.visualization import (
    plot_heatmap_overlay,
    plot_orthogonal_views,
    plot_probability_gauge,
)

logger = get_logger(__name__)

DISCLAIMER = (
    "This application is a research and educational prototype and is **NOT** "
    "a medical diagnostic device. Predictions are generated by an artificial "
    "intelligence model and must not be used as a substitute for evaluation "
    "by a qualified radiologist or physician. Performance on external "
    "patients may differ from performance on research datasets."
)

st.set_page_config(page_title="AI Lung CT Analysis", layout="wide", page_icon="\U0001FA7B")


# --------------------------------------------------------------------------- #
# Caching helpers
# --------------------------------------------------------------------------- #
@st.cache_resource(show_spinner=False)
def get_detector():
    return load_pretrained_model()


@st.cache_resource(show_spinner=False)
def get_classifier():
    return load_classifier()


def cleanup_session_dir(session_dir: Path) -> None:
    import shutil

    shutil.rmtree(session_dir, ignore_errors=True)


# --------------------------------------------------------------------------- #
# Sidebar
# --------------------------------------------------------------------------- #
def render_sidebar():
    st.sidebar.title("AI Lung CT Analysis")
    st.sidebar.caption("Research Prototype for NSCLC CT Analysis")

    st.sidebar.markdown("### Upload CT")
    upload_mode = st.sidebar.radio(
        "Input type", ["NIfTI file (.nii / .nii.gz)", "DICOM series (ZIP)"]
    )

    uploaded_file = None
    if upload_mode.startswith("NIfTI"):
        uploaded_file = st.sidebar.file_uploader("Upload NIfTI file", type=["nii", "gz"])
    else:
        uploaded_file = st.sidebar.file_uploader("Upload DICOM ZIP", type=["zip"])

    st.sidebar.markdown("### Analysis Settings")
    score_threshold = st.sidebar.slider("Detection score threshold", 0.1, 0.9, 0.5, 0.05)

    st.sidebar.markdown("### Model Information")
    status = check_model_files()
    st.sidebar.write(f"Device: **{status.device.upper()}**")
    if status.gpu_name:
        st.sidebar.write(f"GPU: {status.gpu_name}")
    st.sidebar.write(
        "Detection weights: "
        + ("✅ Loaded" if status.detection_weights_found else "⚠️ Not found (demo network)")
    )
    st.sidebar.write(
        "NSCLC classifier: "
        + ("✅ Available" if status.classifier_available else "⚠️ Not Available (demo mode)")
    )

    st.sidebar.markdown("### About Dataset")
    st.sidebar.caption(
        "Trained/developed using TCIA NSCLC Radiogenomics (211 subjects) and "
        "NSCLC Radiomics (422 subjects) — both cancer cohorts, not "
        "healthy-vs-cancer datasets. See the Dataset tab for details."
    )

    st.sidebar.markdown("### Disclaimer")
    st.sidebar.warning(DISCLAIMER)

    return uploaded_file, upload_mode, score_threshold


# --------------------------------------------------------------------------- #
# Tabs
# --------------------------------------------------------------------------- #
def render_home_tab():
    st.header("AI Lung CT Analysis")
    st.subheader("Research Prototype for NSCLC CT Analysis")
    st.info(DISCLAIMER)
    st.markdown(
        """
This application demonstrates a research pipeline combining a pretrained
medical-imaging model with radiomic feature extraction for **NSCLC-related**
CT analysis:

1. **CT/DICOM input validation** — checks uploaded scans before processing
2. **Preprocessing** — HU conversion, resampling, windowing, normalization
3. **Lung nodule localization** — pretrained MONAI detection model
4. **Feature extraction** — radiomic (PyRadiomics) + deep-learning features
5. **NSCLC-related prediction** — only when a project-specific classifier is installed
6. **Explainability** — Grad-CAM attention overlays
7. **Clear disclaimers** throughout

Use the **CT Analysis** tab to upload and analyze a scan.
        """
    )


def render_model_info_tab():
    st.header("Model Information")
    status = check_model_files()

    st.markdown("#### Detection Model")
    st.write("**Model:** MONAI Lung Nodule CT Detection")
    st.write("**Framework:** PyTorch + MONAI")
    st.write("**Task:** 3D lung nodule detection")
    st.write("**Training dataset:** LUNA16")
    st.error("This model is not a standalone lung cancer diagnostic model.")
    st.write(
        "Status: "
        + ("Pretrained weights loaded." if status.detection_weights_found else
           "Pretrained weights NOT found — running an untrained demo network "
           "for pipeline demonstration only. Run `python scripts/download_model.py`.")
    )

    st.markdown("#### NSCLC Classifier")
    st.write(
        "NSCLC classifier: "
        + ("**Available**" if status.classifier_available else "**Not Available**")
    )
    if not status.classifier_available:
        st.warning(
            "Demo mode: pretrained nodule detection is available, but "
            "project-specific cancer classification weights are not installed. "
            "See training/README.md to train one."
        )

    st.markdown("#### Compute")
    st.write(f"Device: **{status.device.upper()}**")
    if status.gpu_name:
        st.write(f"GPU: {status.gpu_name}")


def render_dataset_tab():
    st.header("Dataset")
    dataset_cfg = load_dataset_config()
    pos = dataset_cfg.get("positive_dataset", {})

    for collection in pos.get("collections", []):
        st.subheader(collection["display_name"])
        st.write(f"**Subjects:** {collection['subjects']}")
        st.write(f"**Modalities:** {', '.join(collection['modalities'])}")
        st.write(f"**Segmentation available:** {collection['has_segmentation']}")
        st.write(f"**Clinical data available:** {collection['has_clinical']}")
        st.write(f"**Genomic data available:** {collection['has_genomic']}")
        st.markdown(f"[Official TCIA page]({collection['url']})")
        st.divider()

    st.error(
        "**Important Dataset Limitation:** These collections are NSCLC/"
        "lung-cancer cohorts and should not be treated as healthy-vs-cancer "
        "datasets. Every subject in NSCLC Radiogenomics and NSCLC Radiomics "
        "already has NSCLC. A true cancer-vs-no-cancer classifier requires an "
        "additional, separately-sourced negative/healthy cohort (see "
        "configs/dataset.yaml)."
    )


def render_evaluation_tab():
    st.header("Evaluation")
    cfg = load_config()
    report_dir = resolve_path(cfg.get("paths", {}).get("reports_dir", "reports"))
    metrics_path = report_dir / "metrics.json"

    if not metrics_path.exists():
        st.warning(
            "Model evaluation unavailable because a trained project-specific "
            "classifier has not yet been provided."
        )
        st.caption(
            "Run the training pipeline (training/train_classifier.py, then "
            "training/evaluate_model.py) to populate this tab."
        )
        return

    import json

    with metrics_path.open("r", encoding="utf-8") as f:
        metrics = json.load(f)

    if metrics.get("status") != "ok":
        st.warning(metrics.get("message", "Evaluation unavailable."))
        return

    cols = st.columns(4)
    cols[0].metric("Accuracy", f"{metrics['accuracy']:.1%}")
    cols[1].metric("Sensitivity", f"{metrics['sensitivity']:.1%}")
    cols[2].metric("Specificity", f"{metrics['specificity']:.1%}")
    auc = metrics.get("roc_auc")
    cols[3].metric("ROC-AUC", f"{auc:.3f}" if auc is not None else "N/A")

    for fname, caption in [
        ("confusion_matrix.png", "Confusion Matrix"),
        ("roc_curve.png", "ROC Curve"),
        ("pr_curve.png", "Precision-Recall Curve"),
    ]:
        fpath = report_dir / fname
        if fpath.exists():
            st.image(str(fpath), caption=caption, width=400)

    st.caption(
        "Evaluated on a held-out, patient-level test split. Performance on "
        "external patients may differ from performance on research datasets."
    )


def render_about_tab():
    st.header("About")
    st.markdown(
        """
**AI Lung CT Analysis** is an open research prototype demonstrating how a
pretrained medical-imaging model (MONAI lung nodule detection, trained on
LUNA16) can be combined with radiomic and deep-learning features for
NSCLC-related CT analysis, using the TCIA NSCLC Radiogenomics and NSCLC
Radiomics collections for research/model development.

It is built for transparency: every prediction is labeled with its
provenance, the app never fabricates a probability when no trained
classifier is installed, and dataset limitations are surfaced throughout
the interface.

See the project README for installation, training, and evaluation
instructions.
        """
    )
    st.info(DISCLAIMER)


def render_ct_analysis_tab(uploaded_file, upload_mode, score_threshold):
    st.header("Step 1 — Upload CT Scan")

    if uploaded_file is None:
        st.info("Use the sidebar to upload a NIfTI file or a DICOM ZIP archive.")
        return

    session_id = st.session_state.get("session_id")
    if not session_id:
        session_id = str(uuid.uuid4())
        st.session_state["session_id"] = session_id

    cfg = load_config()
    upload_root = resolve_path(cfg.get("paths", {}).get("upload_dir", "runtime/uploads"))
    session_dir = upload_root / session_id
    session_dir.mkdir(parents=True, exist_ok=True)

    suffix = ".zip" if upload_mode.startswith("DICOM") else Path(uploaded_file.name).suffix
    saved_path = session_dir / f"upload{suffix if suffix else ''}"
    if Path(uploaded_file.name).name.lower().endswith(".nii.gz"):
        saved_path = session_dir / "upload.nii.gz"

    with saved_path.open("wb") as f:
        f.write(uploaded_file.getbuffer())

    try:
        ct_volume = load_any(saved_path, workdir=session_dir / "extracted")
    except (UnsupportedInputError, Exception) as exc:  # noqa: BLE001
        st.error(f"Failed to load the uploaded scan: {exc}")
        cleanup_session_dir(session_dir)
        return

    meta = ct_volume.anonymized_meta
    cols = st.columns(4)
    cols[0].metric("File", uploaded_file.name)
    cols[1].metric("Modality", meta.get("modality", "?"))
    cols[2].metric("Slices", meta.get("num_slices", ct_volume.num_slices))
    cols[3].metric(
        "Voxel spacing (mm)",
        f"{ct_volume.spacing[0]:.2f} x {ct_volume.spacing[1]:.2f} x {ct_volume.spacing[2]:.2f}",
    )

    st.header("Step 2 — Analyze")
    run = st.button("Run CT Analysis", type="primary")

    if not run:
        cleanup_session_dir(session_dir)
        return

    progress = st.progress(0, text="Loading CT...")

    try:
        progress.progress(15, text="Preprocessing...")
        preprocessed = preprocess_ct_volume(ct_volume)

        progress.progress(35, text="Detecting pulmonary nodules...")
        detector = get_detector()
        detector.score_threshold = score_threshold
        candidates = detector.detect(preprocessed.array)

        progress.progress(50, text="Extracting ROI...")
        if candidates:
            mask = generate_roi_from_detection(candidates, preprocessed.array.shape)
            cropped_volume, bbox = crop_roi(preprocessed.array, mask, margin_voxels=4)
            cropped_mask, _ = crop_roi(mask, mask, margin_voxels=4)
            roi_stats = calculate_roi_statistics(preprocessed.array, mask, preprocessed.target_spacing)
        else:
            mask = None
            roi_stats = None

        progress.progress(65, text="Extracting features...")
        deep_features = extract_deep_features(preprocessed.array, detector=detector)

        radiomic_features = None
        if mask is not None and mask.sum() > 0:
            try:
                radiomic_features = extract_radiomic_features(
                    preprocessed.array, mask, preprocessed.target_spacing
                )
            except RadiomicsExtractionError as exc:
                logger.warning("Radiomics unavailable: %s", exc)

        progress.progress(80, text="Running classifier...")
        classifier = get_classifier()
        probability = None
        classifier_error = None
        if candidates:
            try:
                feature_vector = deep_features
                probability = classifier.predict_proba(feature_vector)
            except ClassifierUnavailableError as exc:
                classifier_error = str(exc)

        progress.progress(90, text="Generating explanation...")
        _, heatmap = generate_explanation(preprocessed.array, detector=detector)

        progress.progress(100, text="Done.")
        progress.empty()

    except Exception as exc:  # noqa: BLE001
        progress.empty()
        st.error(f"Analysis failed: {exc}")
        logger.exception("Analysis pipeline failed.")
        cleanup_session_dir(session_dir)
        return

    render_results(
        preprocessed, candidates, roi_stats, probability, classifier_error, heatmap, mask
    )

    cleanup_session_dir(session_dir)


def render_results(preprocessed, candidates, roi_stats, probability, classifier_error, heatmap, mask):
    st.header("Step 3 — Results")

    if not candidates:
        st.warning("No candidate nodule regions were detected above the score threshold.")
        return

    result_cols = st.columns(3)
    result_cols[0].metric("Detected candidate regions", len(candidates))
    if roi_stats:
        result_cols[1].metric("Largest candidate diameter", f"{roi_stats.max_diameter_mm:.1f} mm")
        result_cols[2].metric("ROI volume", f"{roi_stats.volume_mm3:.0f} mm³")

    st.subheader("Model-Estimated Prediction")
    if probability is not None:
        risk_label = "High-risk NSCLC pattern" if probability >= 0.5 else "Low-risk NSCLC pattern"
        confidence = (
            "High" if abs(probability - 0.5) > 0.35 else
            "Moderate" if abs(probability - 0.5) > 0.15 else
            "Low"
        )
        st.success(f"**Prediction:** {risk_label}")
        st.plotly_chart(plot_probability_gauge(probability), width='stretch')
        st.write(f"**Confidence:** {confidence}")
        st.caption(
            "This is a model-estimated probability/risk score, not a diagnosis. "
            "See disclaimer below."
        )
    else:
        st.warning(
            classifier_error
            or "NSCLC classifier unavailable. Only nodule detection and feature "
            "extraction were performed."
        )

    st.subheader("Visualization")
    volume = preprocessed.array
    d, h, w = volume.shape
    default_slice = candidates[0].z if candidates else d // 2

    slice_idx = st.slider("Slice", 0, d - 1, int(np.clip(default_slice, 0, d - 1)))
    slice_col1, slice_col2 = st.columns(2)
    if slice_col1.button("Previous Slice") and slice_idx > 0:
        slice_idx -= 1
    if slice_col2.button("Next Slice") and slice_idx < d - 1:
        slice_idx += 1
    if st.button("Jump to Detected Region"):
        slice_idx = int(np.clip(candidates[0].z, 0, d - 1))

    fig1 = plot_orthogonal_views(volume, slice_idx, h // 2, w // 2)
    st.pyplot(fig1)

    fig2 = plot_heatmap_overlay(volume, heatmap, slice_idx)
    st.pyplot(fig2)
    st.caption(
        "Heatmap shows model attention / feature attribution, not proof of cancer."
    )

    st.info(DISCLAIMER)


def main():
    uploaded_file, upload_mode, score_threshold = render_sidebar()

    tabs = st.tabs(
        ["Home", "CT Analysis", "Model Information", "Dataset", "Evaluation", "About"]
    )

    with tabs[0]:
        render_home_tab()
    with tabs[1]:
        render_ct_analysis_tab(uploaded_file, upload_mode, score_threshold)
    with tabs[2]:
        render_model_info_tab()
    with tabs[3]:
        render_dataset_tab()
    with tabs[4]:
        render_evaluation_tab()
    with tabs[5]:
        render_about_tab()


if __name__ == "__main__":
    main()
